import type { CaseStudy, Item } from "@/lib/ngn/schemas";
import { validateCaseStudy, validateItem } from "@/lib/ngn/validate";
import { sampleSet } from "@/lib/onboarding/sampleBank";
import { toCaseStudyRow, toItemRow, type ItemRow } from "./itemRows";

// Fixed ids so a local `supabase db reset` always produces the same rows. Local seed only.
const ORG_ID = "00000000-0000-4000-8000-000000000001";
const BANK_ID = "00000000-0000-4000-8000-000000000002";
const CASE_STUDY_ID = "00000000-0000-4000-8000-000000000003";
const itemId = (index: number) =>
  `00000000-0000-4000-8000-${String(100 + index).padStart(12, "0")}`;

const JSON_QUOTE = "$json$";

/**
 * Builds supabase/seed.sql from the sample fixtures: one org, one published "Samples" bank with
 * every canonical item, the Trend item and the case study. The committed file is checked
 * against this output in seed.test.ts.
 */
export function buildSampleSeedSql(): string {
  // The same set the Get started checklist imports as "Sample bank" (#265).
  const sample = sampleSet();
  const standalone = sample.items.map(mustItem);
  const caseStudy = toCaseStudyRow(mustCaseStudy(sample.caseStudy));
  const rows = [...standalone.map(toItemRow), ...caseStudy.items];
  const caseStudyItemIds = caseStudy.items.map((_, i) => itemId(standalone.length + i));

  return [
    "-- Generated by src/lib/supabase/seed.ts from the sample fixtures. Do not edit by hand.",
    "-- Regenerate: UPDATE_SEED=1 pnpm exec vitest run src/lib/supabase/seed.test.ts",
    "",
    `insert into public.orgs (id, name) values (${sql(ORG_ID)}, 'LeaRN');`,
    "",
    `insert into public.item_banks (id, org_id, name) values (${sql(BANK_ID)}, ${sql(ORG_ID)}, 'Samples');`,
    "",
    "insert into public.items",
    "  (id, bank_id, org_id, type, cjmm_step, tags, version, status, content, answer_key, rationale, scoring)",
    "values",
    rows.map((row, i) => itemValues(itemId(i), row)).join(",\n") + ";",
    "",
    "insert into public.case_studies (id, bank_id, org_id, title, ehr, tags, status)",
    "values (",
    `  ${sql(CASE_STUDY_ID)}, ${sql(BANK_ID)}, ${sql(ORG_ID)}, ${sql(caseStudy.title)},`,
    "  -- ehr",
    `${jsonb(caseStudy.ehr)},`,
    `  ${textArray(caseStudy.tags)}, 'published'`,
    ");",
    "",
    "insert into public.case_study_items (case_study_id, org_id, bank_id, position, item_id)",
    "values",
    caseStudyItemIds
      .map(
        (id, i) =>
          `  (${sql(CASE_STUDY_ID)}, ${sql(ORG_ID)}, ${sql(BANK_ID)}, ${i + 1}, ${sql(id)})`,
      )
      .join(",\n") + ";",
    "",
  ].join("\n");
}

function itemValues(id: string, row: ItemRow): string {
  return [
    "(",
    `  ${sql(id)}, ${sql(BANK_ID)}, ${sql(ORG_ID)}, ${sql(row.type)}, ${row.cjmm_step ?? "null"},`,
    `  ${textArray(row.tags)}, ${row.version}, 'published',`,
    "  -- content",
    `${jsonb(row.content)},`,
    "  -- answer_key",
    `${jsonb(row.answer_key)},`,
    "  -- rationale",
    `${jsonb(row.rationale)},`,
    "  -- scoring",
    `${jsonb(row.scoring)}`,
    ")",
  ].join("\n");
}

function mustItem(input: unknown): Item {
  const result = validateItem(input);
  if (!result.ok) throw new Error(`sample item is invalid:\n${result.errors.join("\n")}`);
  return result.value;
}

function mustCaseStudy(input: unknown): CaseStudy {
  const result = validateCaseStudy(input);
  if (!result.ok) throw new Error(`sample case study is invalid:\n${result.errors.join("\n")}`);
  return result.value;
}

function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function textArray(values: readonly string[]): string {
  return values.length ? `array[${values.map(sql).join(", ")}]::text[]` : "'{}'::text[]";
}

function jsonb(value: unknown): string {
  const text = JSON.stringify(value);
  if (text.includes(JSON_QUOTE)) throw new Error(`seed JSON may not contain ${JSON_QUOTE}`);
  return `${JSON_QUOTE}${text}${JSON_QUOTE}::jsonb`;
}
